feat: ping and ready endpoints
Informasjonsforvaltning/fdk-rdf-parser-service pull request #2
Opened 2023-02-23 16:05 UTC by terjesyl

feat: rabbit listener

2023-02-24 07:01 UTC, NilsOveTen requested changes

2023-02-24 07:01 UTC, NilsOveTen commented on noxfile.py
> +    session.run("python", "openapi.py")
Denne mangler openapi.py
```suggestion
@session(python=python_versions[0])
def openapi(session: Session) -> None:
    """Generate API spec from code."""
    session.install(".")
    session.install("PyYAML")
    session.run("python", "openapi.py")
```

2023-02-27 11:19 UTC, NilsOveTen commented on fdk_rdf_parser_service/app.py
> +    logging.getLogger("chardet.charsetprober").setLevel(logging.INFO)
Er dette nødvendig mtp all log-konfigureringen du gjør i gunicorn_config?

2023-02-27 11:19 UTC, NilsOveTen commented on fdk_rdf_parser_service/rabbit/consumer.py
> +    logging.info("Rabbit message received.")
Litt mer nyttig å vite hvilken melding du har fått, så kan vi se i staging at du konsumerer alle meldingene du skal og ikke andre. Så ta med routing_key her

2023-02-27 11:19 UTC, NilsOveTen commented on noxfile.py
> +nox.options.reuse_existing_virtualenvs = False
Tinge går vel ikke kjappere når du har `reuse_existing_virtualenvs = False`?

2023-02-27 11:19 UTC, NilsOveTen commented on noxfile.py
> +# def integration_tests(session: Session) -> None:
Du kan fint slenge på noen enkle integrasjonstester som sjekker at du får 200 fra ping og ready

2023-02-27 12:30 UTC, terjesyl commented on fdk_rdf_parser_service/rabbit/consumer.py
> +    logging.info("Rabbit message received.")
Ok! Skal legge det inn som logging.info, brukte print tidligere.

2023-02-27 12:33 UTC, terjesyl commented on fdk_rdf_parser_service/app.py
> +    logging.getLogger("chardet.charsetprober").setLevel(logging.INFO)
Uuuusikker, tror dette ble hentet fra aiohttp-eksempelprosjektet. Hvis man kjører opp uten gunicorn (lokalt f.eks.) trengs det kanskje?

2023-03-24 11:13 UTC, NilsOveTen approved these changes
squash plz

2023-03-24 11:13 UTC, NilsOveTen approved these changes

2023-03-24 11:15 UTC, merged